#!/usr/bin/env bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

root=`dirname $0`

if [[ "$ISOLATE_PATH" == "" ]]; then # if no environment variable set
  if [[ ! -f "ISOLATE_PATH" ]]; then
    echo ../moe-cms/obj/isolate/isolate > ISOLATE_PATH
  fi
  ISOLATE_PATH=`cat $root/ISOLATE_PATH`
fi

sudo -u\#$SUDO_UID -g\#$SUDO_GID mkdir $root/bin -p
sudo -u\#$SUDO_UID -g\#$SUDO_GID mkdir $root/tmp -p

echo "Copying isolate from $ISOLATE_PATH"
cp $ISOLATE_PATH $root/bin/isolate

chmod 754 $root/bin/isolate
echo "Allow group $SUDO_GID(`awk -F':' -v v_gid="$SUDO_GID" '{ if ( $3 == v_gid ) {print $1} }' /etc/group`) to execute isolate"
chgrp $SUDO_GID $root/bin/isolate

echo "Setting suid on isolate"
chmod +s $root/bin/isolate

echo "Setting up temporary root file"
echo "Sensitive info" > $root/tmp/sensitive-system-file

echo "Setting up mock cron.daily"
mkdir $root/tmp/cron.daily -p
echo "# Benign script"> $root/tmp/cron.daily/evil-bash-script

echo "Done!"

